// axe-core WCAG 2.0/2.1 A + AA scan of each main state. Usage: CHROME_PATH=... BASE_URL=... node scripts/a11y.mjs
import { chromium } from "playwright-core";
import { readFileSync } from "node:fs";
const BASE = process.env.BASE_URL || "http://127.0.0.1:8787";
const CHROME = process.env.CHROME_PATH;
if (!CHROME) throw new Error("Set CHROME_PATH to a Chrome or Chromium executable");
const axe = readFileSync("node_modules/axe-core/axe.min.js", "utf8");
const browser = await chromium.launch({ executablePath: CHROME, headless: true });
const page = await (await browser.newContext({ viewport: { width: 1280, height: 900 } })).newPage();
let total = 0;
async function scan(label) {
  await page.waitForTimeout(400);
  await page.evaluate(axe);
  const r = await page.evaluate(async () => await window.axe.run(document, { runOnly: { type: "tag", values: ["wcag2a", "wcag2aa", "wcag21a", "wcag21aa"] } }));
  total += r.violations.length;
  console.log(`${label}: ${r.violations.length} violations, ${r.passes.length} rules passed, ${r.incomplete.length} need review`);
  for (const v of r.violations) console.log(`  - ${v.id} (${v.impact}): ${v.nodes.length} node(s) e.g. ${v.nodes[0].target.join(" ")}`);
}
const btn = (name) => page.getByRole("button", { name, exact: true });
await page.goto(BASE + "/");
await scan("empty import");
await btn("Validate & import").click();
await scan("empty-input error");
await btn("Load synthetic sample").click();
await btn("Validate & import").click();
await scan("import result with row errors");
await btn("Open handoff queue").click();
await scan("queue");
await page.getByRole("button", { name: "Open 100106" }).click();
await btn("Fixture: expected reply").click();
await scan("packet: missing evidence + refusal");
await page.selectOption("#pick", "100102");
await btn("Fixture: invented source").click();
await scan("packet: rejected response");
await btn("Fixture: expected reply").click();
await btn("Continue to human approval").click();
await page.fill("#approver", "Ayo Ahmed"); await page.check("#reviewed");
await btn("Approve handoff").click(); await btn("Run simulated write").click(); await btn("Simulated fresh read & verify").click();
await scan("approve/write/verify");
await page.locator(".nav", { hasText: "SLA" }).click();
await scan("reports");
await page.locator(".nav", { hasText: "Spec" }).click();
await btn("Run regression").click();
await scan("regression");
await page.keyboard.press("Tab");
const outline = await page.evaluate(() => getComputedStyle(document.activeElement).outlineStyle);
console.log(`focused element has visible outline: ${outline !== "none"} (${outline})`);
await browser.close();
console.log(`TOTAL axe violations: ${total}`);
process.exit(total ? 1 : 0);
